name: 📝 작업 이슈
description: 새로운 브랜치를 생성할 작업 단위가 있을 때 작성해주세요.
labels: []
assignees: []

body:
  - type: textarea
    id: description
    attributes:
      label: 📌 작업 설명
      description: 어떤 작업을 하려는 건가요?
      placeholder: 예) 사용자 로그인 시 토큰이 만료되면 자동 로그아웃 처리
    validations:
      required: true

  - type: textarea
    id: checklist
    attributes:
      label: ✅ 작업 세부
      description: 어떤 세부 작업이 필요한가요?
      placeholder: |
        - 세부 작업1
    validations:
      required: false
